#!/bin/sh
### BEGIN INIT INFO
# Provides:          gydra
# Required-Start:    $local_fs $network $alsa-utils $time $syslog
# Required-Stop:     $local_fs $network $alsa-utils $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Play special network audio stream
### END INIT INFO

SCRIPT="/usr/bin/gydra -m real"
RUNAS=root

PIDFILE=/var/run/gydra.pid
LOGFILE=/var/log/gydra.log

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service gydra' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service gydra started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service gydra' >&2
  # Send Ctrl+C signal for graceful shutdown
  kill -s INT $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service gydra stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f gydra remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
